
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Nov 30 23:36:14 PST 2004
//----------------------------------------------------

package com.habibi.compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IF_ELSE_STAT = 62;
  public static final int INT_LIST = 53;
  public static final int DIVEQ = 42;
  public static final int printf = 3;
  public static final int STRING_LITERAL = 50;
  public static final int GTEQ = 36;
  public static final int MULT = 10;
  public static final int main = 2;
  public static final int CHAR = 7;
  public static final int LTEQ = 35;
  public static final int MODEQ = 43;
  public static final int LPAREN = 15;
  public static final int INT = 6;
  public static final int IN_LIST = 67;
  public static final int FOR_STAT = 59;
  public static final int FOR = 22;
  public static final int MINUS = 28;
  public static final int RPAREN = 16;
  public static final int CHARACTER_LITERAL = 48;
  public static final int AND = 39;
  public static final int NOT = 30;
  public static final int SEMICOLON = 9;
  public static final int LT = 33;
  public static final int C_LIST = 69;
  public static final int OR = 40;
  public static final int UNARYMINUS = 29;
  public static final int ASSIGN_STAT = 63;
  public static final int DCL_PART = 52;
  public static final int COMMA = 11;
  public static final int FLOAT_LIST = 55;
  public static final int PREPLUSPLUS = 23;
  public static final int DIV = 31;
  public static final int PLUSEQ = 44;
  public static final int NUMBERSIGN = 18;
  public static final int SCANF_STAT = 66;
  public static final int MINUSEQ = 45;
  public static final int PLUS = 27;
  public static final int IF = 19;
  public static final int CHAR_LIST = 54;
  public static final int I_LIST = 70;
  public static final int EOF = 0;
  public static final int WHILE_STAT = 58;
  public static final int OUT_LIST = 65;
  public static final int error = 1;
  public static final int IF_STAT = 61;
  public static final int EQEQ = 37;
  public static final int MULTEQ = 41;
  public static final int MOD = 32;
  public static final int EQ = 14;
  public static final int POSTMINUSMINUS = 26;
  public static final int POSTPLUSPLUS = 24;
  public static final int GOTO_STAT = 60;
  public static final int COLON = 17;
  public static final int FLOATING_POINT_LITERAL = 47;
  public static final int LBRACE = 12;
  public static final int ELSE = 20;
  public static final int EXECUTION_PART = 56;
  public static final int GOTO = 5;
  public static final int PRINTF_STAT = 64;
  public static final int WHILE = 21;
  public static final int FLOAT = 8;
  public static final int RBRACE = 13;
  public static final int BODY = 51;
  public static final int F_LIST = 68;
  public static final int PREMINUSMINUS = 25;
  public static final int LABELED_STAT = 57;
  public static final int GT = 34;
  public static final int scanf = 4;
  public static final int NOTEQ = 38;
  public static final int IDENTIFIER = 49;
  public static final int INTEGER_LITERAL = 46;
}

